---
- src: https://github.com/redhat-cop/openshift-applier
  version: master
  
# The git repo for this project
- src: https://github.com/${GITHUB_ACCOUNT}/openshift-gitops-lab.git
  name: self
  version: master
